//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeCalculator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecipeCalculatorEntities : DbContext
    {
        public RecipeCalculatorEntities()
            : base("name=RecipeCalculatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tblIngredient> tblIngredients { get; set; }
        public virtual DbSet<tblNutrition> tblNutritions { get; set; }
        public virtual DbSet<tblRecipeUser> tblRecipeUsers { get; set; }
        public virtual DbSet<tblStandardRecipe> tblStandardRecipes { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<tblUnit> tblUnits { get; set; }
        public virtual DbSet<tblStandardRecipeIngredient> tblStandardRecipeIngredients { get; set; }
        public virtual DbSet<tblIngredientNutrition> tblIngredientNutritions { get; set; }
        public virtual DbSet<tblYieldFactor> tblYieldFactors { get; set; }
    }
}
