//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNutrition
    {
        public tblNutrition()
        {
            this.tblIngredientNutritions = new HashSet<tblIngredientNutrition>();
        }
    
        public int id { get; set; }
        public string nutrition_name { get; set; }
        public string unit { get; set; }
        public string tag_name { get; set; }
    
        public virtual ICollection<tblIngredientNutrition> tblIngredientNutritions { get; set; }
    }
}
