//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStandardRecipeIngredient
    {
        public int id { get; set; }
        public int standard_recipe_id { get; set; }
        public int ingredient_id { get; set; }
        public decimal weight { get; set; }
        public string unit_name { get; set; }
    
        public virtual tblIngredient tblIngredient { get; set; }
        public virtual tblStandardRecipe tblStandardRecipe { get; set; }
    }
}
